### ISSUE TITLE
Complier tests are currently failing

### ISSUE THREAD

**Issue by justinmclean** [apache/royale-asjs#41]
[INFO] Apache Royale: Compiler: Compiler .................. FAILURE

Tests in error: 
  MXMLComponentNodeTests.MXMLComponentNode_Sprite:95->getMXMLComponentNode:42->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLComponentNodeTests.MXMLComponentNode_className_Sprite:113->getMXMLComponentNode:42->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLComponentNodeTests.MXMLComponentNode_className_id_Sprite_width_height:151->getMXMLComponentNode:42->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLComponentNodeTests.MXMLComponentNode_empty1:60->getMXMLComponentNode:42->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLComponentNodeTests.MXMLComponentNode_empty2:77->getMXMLComponentNode:42->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLComponentNodeTests.MXMLComponentNode_id_Sprite:131->getMXMLComponentNode:42->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLDesignLayerNodeTests.MXMLDesignLayerNode_empty1:54->getMXMLDesignLayerNode:40->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLDesignLayerNodeTests.MXMLDesignLayerNode_empty2:67->getMXMLDesignLayerNode:40->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLDesignLayerNodeTests.MXMLDesignLayerNode_empty3:80->getMXMLDesignLayerNode:40->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLDesignLayerNodeTests.MXMLDesignLayerNode_id_visible_alpha:93->getMXMLDesignLayerNode:40->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLDesignLayerNodeTests.MXMLDesignLayerNode_two_children:112->getMXMLDesignLayerNode:40->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLHTTPServiceNodeTests.MXMLHTTPServiceNode_postRequest:60->getMXMLHTTPServiceNode:41->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLRemoteObjectNodeTests.MXMLRemoteObjectNode_postRequest:61->getMXMLRemoteObjectNode:41->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLStateNodeTests.MXMLStateNode_oneState:72->getMXMLStateNode:54->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime
  MXMLWebServiceNodeTests.MXMLWebServiceNode_twoOperations:58->getMXMLWebServiceNode:41->MXMLNodeBaseTests.getMXMLFileNodeWithFlex:112->MXMLNodeBaseTests.getMXMLFileNode:147 » Runtime

Tests run: 375, Failures: 0, Errors: 15, Skipped: 26

**Comment by justinmclean** [comment]
I've not see any changes to the compile repo and "mvn compile" still fails. What's your reason for closing this?

**Comment by justinmclean** [comment]
To replicate run these command in royale-compiler repo
mvn clean install -P utils
mvn clean install

**Comment by Harbs** [comment]
When #17 is closed this should be fixed.

**Comment by justinmclean** [comment]
But it's not currently so I suggest this is reopened until #17 is fixed.

**Comment by justinmclean** [comment]
The rename branches have been merged into develop but the tests are still failing. I suggest that this ticket be reopened.
