### ISSUE TITLE
mx:TabNavigator and mx:VBox Data is not shown in New SDk

### ISSUE THREAD

**Issue by pashminakazi** [apache/royale-asjs#479]
First-time when i open tabs data is shown in all tabs, 2nd-time data is not shown
https://paste.apache.org/nexlc

**Comment by pashminakazi** [comment]
I have downloaded SDK on 02-oct-2019
First-time when i open tabs data is shown in all tabs, 2nd-time data is not shown
https://paste.apache.org/nexlc
![Output3](https://user-images.githubusercontent.com/42200979/66204973-9f798d80-e6c5-11e9-8354-5c4803e980bb.gif)
Please help
Thanks

**Comment by piotrzarzycki21** [comment]
@pashminakazi Fix has been pushed for that. Next build will contains it. Let me if it's working for you.

**Comment by piotrzarzycki21** [comment]
Following build contains fix: [3634](http://apacheroyaleci.westus2.cloudapp.azure.com:8080/job/royale-asjs_jsonly/3634/)

**Comment by alinakazi** [comment]
Thanks piotr. I  will check these fixes tomorrow in the morning 11 am PST .
And confirm its functionality to you.

**Comment by alinakazi** [comment]
Pashmina is testing these commits

**Comment by piotrzarzycki21** [comment]
> Pashmina is testing these commits

How it goes ? Did you see content ?

**Comment by alinakazi** [comment]
Issue has been fixed. Thanks

**Comment by pashminakazi** [comment]
Thanks

**Comment by pashminakazi** [comment]
Issue not resolved
![image](https://user-images.githubusercontent.com/42200979/66746084-4b776180-ee9a-11e9-8f92-29d32c6c2212.png)
![image](https://user-images.githubusercontent.com/42200979/66746521-77471700-ee9b-11e9-8cc5-7280b2e94c2c.png)

![ViewStack Exception2-New](https://user-images.githubusercontent.com/42200979/66746777-313e8300-ee9c-11e9-94c0-3be12ee57c14.gif)

**Comment by piotrzarzycki21** [comment]
> Issue not resolved
> ![image](https://user-images.githubusercontent.com/42200979/66746084-4b776180-ee9a-11e9-8f92-29d32c6c2212.png)
> ![image](https://user-images.githubusercontent.com/42200979/66746521-77471700-ee9b-11e9-8cc5-7280b2e94c2c.png)
> 
> ![ViewStack Exception2-New](https://user-images.githubusercontent.com/42200979/66746777-313e8300-ee9c-11e9-94c0-3be12ee57c14.gif)

Ok so It is working in a simple attached example to this issue, but doesn't work in your application - Yes ?

**Comment by piotrzarzycki21** [comment]
I just checked and attached example does work, there must be something else on your sight.

**Comment by pashminakazi** [comment]
@piotrzarzycki21 Yes,Its working in simple example but in our application its not working

**Comment by pashminakazi** [comment]
@piotrzarzycki21 If you have time tomorrow,Please have a look at our application's TabNavigator in AnyDesk session that why it is throwing exception : Maximum call stack size exceeded
Thanks

**Comment by piotrzarzycki21** [comment]
> @piotrzarzycki21 If you have time tomorrow,Please have a look at our application's TabNavigator in AnyDesk session that why it is throwing exception : Maximum call stack size exceeded
> Thanks

That is an option, but if you prepare example which contains in each tab what I see on the screenshot - I may be able to look into that today evening and fix. Tomorrow you may get solution and won't waste time on session with me.

**Comment by pashminakazi** [comment]
This Example contains each tab what you see in previous file
File : https://paste.apache.org/yko15
Output : 
![TabNavigator like app](https://user-images.githubusercontent.com/42200979/66824314-7b3d6c80-ef61-11e9-8128-1249c393a626.gif)
![image](https://user-images.githubusercontent.com/42200979/66824325-81334d80-ef61-11e9-85fd-9902afeb77bd.png)

**Comment by piotrzarzycki21** [comment]
Wonderful! I won't have to debug trough the session cause it's reproducible in provided example. Thanks!

**Comment by pashminakazi** [comment]
@piotrzarzycki21
Ur welcome

**Comment by piotrzarzycki21** [comment]
I have spent some time on that and cannot find cause of issue yet. I know that when setup selectedIndex [here](https://github.com/apache/royale-asjs/blob/21c2cdfcfb4599b0bd2c111b7bbedad3b388757f/frameworks/projects/MXRoyale/src/main/royale/mx/containers/beads/TabNavigatorView.as#L196) and invalidateSize is happen [here](https://github.com/apache/royale-asjs/blob/21c2cdfcfb4599b0bd2c111b7bbedad3b388757f/frameworks/projects/MXRoyale/src/main/royale/mx/containers/ViewStack.as#L1274) it causes Maximum stack trace overflow. When comment out that part exception doesn't occur anymore, but content of the tabs is hidden.

**Comment by piotrzarzycki21** [comment]
Another session with that issue and I'm a bit closer to cause of the issue. Error which you are seeing is being caused by CheckBox. If you remove check boxes from tab containers - which of course not an option everything will be working. I think this is somehow related to event "layoutNedded" dispatched during Tab switch. 
Unfortunately I will have time to look into that again on Monday - I will be unavailable from tomorrow. I did prepare short example, so maybe @yishayw will have capacity to look again into that. 

Scenario:
1) Click on Tab1
2) Click on Tab2
3) Click on Tab1 and later on Tab2

Maximum call stack size exceeded occurs.
Example: https://paste.apache.org/32ao4

**Comment by piotrzarzycki21** [comment]
@alinakazi , @pashminakazi Check newest build 66 of Royale. I have pushed some changes which seems to resolve issue, so pull newest changes or use that build when it will be ready.

**Comment by pashminakazi** [comment]
@piotrzarzycki21 Thanks,I am testing these commits

**Comment by piotrzarzycki21** [comment]
Commits specifically is related to CheckBox - it was problem inside that component, so take a look if it's still displays and working correctly.

**Comment by pashminakazi** [comment]
@piotrzarzycki21 Issue Resolved.
Thank u so much

**Comment by piotrzarzycki21** [comment]
This issue may needed different solution, but output would the same for you - working app. We will see.
