### ISSUE TITLE
Exceptions on selection of Date 

### ISSUE THREAD

**Issue by alinakazi** [apache/royale-asjs#590]
Go to Inventory Module

Go to Setups ->Inventory schedule setup
file name : dbzInventorySchedulingSetup

On selection of From Date
![image](https://user-images.githubusercontent.com/36731338/69526807-db8bda80-0f1f-11ea-960e-4185b68cac2e.png)

exceptions on debug console
![image](https://user-images.githubusercontent.com/36731338/69526870-f9593f80-0f1f-11ea-93e7-5687c2d37d66.png)

**Comment by aharui** [comment]
This should now be fixed by 9b812c102527b28ff9bb33e91ca4ee072f0d82ba

**Comment by alinakazi** [comment]
still facing same issue
![image](https://user-images.githubusercontent.com/36731338/69626728-0fd5c880-0ffe-11ea-819c-cf877254e117.png)

**Comment by aharui** [comment]
I cannot reproduce on the VDI.  From the screenshot with NaN for dates, I would guess that there was some other exception that screwed up the initialization of the DateField.  If there are earlier exceptions, you cannot guarantee that the most recent exception is a problem.

If you can reproduce, please provide more detailed steps.
